#!/usr/bin/env bash
set -euo pipefail

ROOT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
ENV_FILE="${ROOT_DIR}/.env.guiagent_v2.local"

if [[ ! -f "${ENV_FILE}" ]]; then
  echo "env file not found: ${ENV_FILE}" >&2
  return 1 2>/dev/null || exit 1
fi

set -a
# shellcheck disable=SC1090
source "${ENV_FILE}"
set +a

if [[ -z "${AGENT_BROWSER_PROJECT_DIR:-}" ]]; then
  if [[ -d "${ROOT_DIR}/third_party/agent-browser" ]]; then
    export AGENT_BROWSER_PROJECT_DIR="${ROOT_DIR}/third_party/agent-browser"
  else
    export AGENT_BROWSER_PROJECT_DIR="${ROOT_DIR}/demo/agent-browser"
  fi
fi
export AGENT_BROWSER_PREFER_LOCAL="${AGENT_BROWSER_PREFER_LOCAL:-1}"
export AGENT_BROWSER_FORCE_NATIVE="${AGENT_BROWSER_FORCE_NATIVE:-1}"
export GUIAGENT_V2_FORCE_DISABLE_THINKING_FOR_STRUCTURED="${GUIAGENT_V2_FORCE_DISABLE_THINKING_FOR_STRUCTURED:-1}"
export GUIAGENT_V2_FORCE_JSON_RESPONSE_FOR_STRUCTURED="${GUIAGENT_V2_FORCE_JSON_RESPONSE_FOR_STRUCTURED:-1}"
export GUIAGENT_V2_MODEL_NODE_TIMEOUT_SEC="${GUIAGENT_V2_MODEL_NODE_TIMEOUT_SEC:-35}"

echo "[env] loaded: ${ENV_FILE}"
echo "[env] GUIAGENT_V2_API_TYPE=${GUIAGENT_V2_API_TYPE:-}"
echo "[env] GUIAGENT_V2_INTENT_PARSER_MODEL=${GUIAGENT_V2_INTENT_PARSER_MODEL:-}"
echo "[env] GUIAGENT_V2_WEB_REPLAN_MODEL=${GUIAGENT_V2_WEB_REPLAN_MODEL:-}"
echo "[env] GUIAGENT_V2_ASSERTION_REPAIR_MODEL=${GUIAGENT_V2_ASSERTION_REPAIR_MODEL:-}"
echo "[env] DASHSCOPE_API_KEY configured=$([[ -n "${DASHSCOPE_API_KEY:-}" ]] && echo true || echo false)"
echo "[env] AGENT_BROWSER_PROJECT_DIR=${AGENT_BROWSER_PROJECT_DIR:-}"
echo "[env] AGENT_BROWSER_FORCE_NATIVE=${AGENT_BROWSER_FORCE_NATIVE:-}"
echo "[env] GUIAGENT_V2_FORCE_DISABLE_THINKING_FOR_STRUCTURED=${GUIAGENT_V2_FORCE_DISABLE_THINKING_FOR_STRUCTURED:-}"
echo "[env] GUIAGENT_V2_FORCE_JSON_RESPONSE_FOR_STRUCTURED=${GUIAGENT_V2_FORCE_JSON_RESPONSE_FOR_STRUCTURED:-}"
echo "[env] GUIAGENT_V2_MODEL_NODE_TIMEOUT_SEC=${GUIAGENT_V2_MODEL_NODE_TIMEOUT_SEC:-}"
